# Generated by Django 2.2.14 on 2020-08-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200803_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='availability',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
