# Generated by Django 2.2.15 on 2020-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200804_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.TextField(default='', verbose_name='Контакты'),
        ),
    ]
