# Generated by Django 2.2.15 on 2020-08-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
