# Generated by Django 2.2.15 on 2020-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
