# Generated by Django 2.2.15 on 2021-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210111_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='Фото', max_length=200, verbose_name='Название'),
        ),
    ]
