version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - net
  web:
    container_name: web
    build:
      context: .
    entrypoint: ['./start.sh']
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - '8000'
    depends_on:
      - db
    networks:
      - net
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - net
networks:
  net:
volumes:
  media_volume:
  static_volume:
  db_volume: